package ca.mcgill.ecse.climbsafe.javafx.fxml.controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.input.MouseEvent;

import javafx.scene.input.DragEvent;

import javafx.scene.control.ChoiceBox;

public class EquipmentController {
	@FXML
	private Button AddEquipmentButton;
	@FXML
	private Button DeleteEquipmentButton;
	@FXML
	private ChoiceBox EquipmentDropDownBar;
	@FXML
	private ChoiceBox EquipmentBundleDropDownBar;
	@FXML
	private Button AddBundleButton;
	@FXML
	private Button DeleteBundleButton;

	// Event Listener on Button[#AddEquipmentButton].onAction
	@FXML
	public void addEquipment(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#DeleteEquipmentButton].onAction
	@FXML
	public void deleteEquipment(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ChoiceBox[#EquipmentDropDownBar].onDragDetected
	@FXML
	public void showAllEquipments(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ChoiceBox[#EquipmentDropDownBar].onDragDone
	@FXML
	public void selectEquipment(DragEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ChoiceBox[#EquipmentBundleDropDownBar].onDragDetected
	@FXML
	public void showAllEquipmentBundles(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ChoiceBox[#EquipmentBundleDropDownBar].onDragDone
	@FXML
	public void selectEquipmentBundle(DragEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#AddBundleButton].onAction
	@FXML
	public void addEquipmentBundle(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#DeleteBundleButton].onAction
	@FXML
	public void deleteEquipmentBundle(ActionEvent event) {
		// TODO Autogenerated
	}
}
