package ca.mcgill.ecse.climbsafe.javafx.fxml.controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class GuideController {
	@FXML
	private Button AddGuideButton;
	@FXML
	private Button RemoveGuideButton;
	@FXML
	private TextField UserNameTextField;
	@FXML
	private TextField EmailText;
	@FXML
	private Button UpdateGuideButton;

	// Event Listener on Button[#AddGuideButton].onAction
	@FXML
	public void addGuide(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#RemoveGuideButton].onAction
	@FXML
	public void removeGuide(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#UserNameTextField].onAction
	@FXML
	public void enterUserName(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#EmailText].onAction
	@FXML
	public void enterEmail(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#UpdateGuideButton].onAction
	@FXML
	public void updateGuide(ActionEvent event) {
		// TODO Autogenerated
	}
}
