package ca.mcgill.ecse.climbsafe.javafx.fxml.controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class HotelController {
	@FXML
	private Button AddHotelButton;
	@FXML
	private Button RemoveHotelButton;
	@FXML
	private TextField HotelNameTextField;
	@FXML
	private Button UpdateHotelButton;

	// Event Listener on Button[#AddHotelButton].onAction
	@FXML
	public void addHotel(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#RemoveHotelButton].onAction
	@FXML
	public void removeHotel(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#HotelNameTextField].onAction
	@FXML
	public void enterHotelName(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#UpdateHotelButton].onAction
	@FXML
	public void updateHotel(ActionEvent event) {
		// TODO Autogenerated
	}
}
