package ca.mcgill.ecse.climbsafe.javafx.fxml.controllers;

import ca.mcgill.ecse.climbsafe.controller.ClimbSafeFeatureSet1Controller;
import ca.mcgill.ecse.climbsafe.controller.ClimbSafeFeatureSet7Controller;
import ca.mcgill.ecse.climbsafe.javafx.fxml.main.ClimbSafeFxmlView;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.event.ActionEvent;

public class HotelController {
	@FXML
	private Button AddHotelButton;
	@FXML
	private Button RemoveHotelButton;
	@FXML
	private TextField HotelNameTextField;
	@FXML
	private TextField OldHotelNameTextField;
	@FXML
	private TextField NewHotelNameTextField;
	@FXML
	private TextField NewHotelAddressTextField;
	@FXML
	private TextField NewStarRatingTextField;
	@FXML
	private Button UpdateHotelButton;
	@FXML
	private TextField HotelAddressTextField;
	@FXML
	private TextField  StarRatingTextField;
	@FXML
	private TextField  HotelDeleteTextField;
	// Event Listener on Button[#AddHotelButton].onAction
	@FXML
	public void addHotel(ActionEvent event) {
		
		String name = HotelNameTextField.getText();
	    String address = HotelAddressTextField.getText();
	    String nrStars = StarRatingTextField.getText();
	    
	    if (name == null || name.trim().isEmpty()) {
	    	ViewUtils.showError("Please input a valid hotel name");
	    } 
	    else if (address == null || address.trim().isEmpty()) {
	    	ViewUtils.showError("Please input a valid hotel address");
		}
	    else if (nrStars == null || rating.trim().isEmpty()) {
	    	ViewUtils.showError("Please input a valid hotel rating");
		}
	    else {
	      // reset the driver text field if success
	      if (ViewUtils.callController(() -> 
	      ClimbSafeFeatureSet7Controller.addHotel(String name, String address, Integer.valueOf(nrStars)))) {
	    	  ViewUtils.makePopupWindow("Hotel Added", name + " has been added successfully.");
	    	  
	    	  HotelNameTextField.setText("");
	    	  HotelAddressTextField.setText("");
	    	  StarRatingTextField.setText("");
	      }
	    }
	}
	    
	// Event Listener on Button[#RemoveHotelButton].onAction
	@FXML
	public void removeHotel(ActionEvent event) {
		// TODO Autogenerated
		String name= HotelDeleteTextField.getText();
		
		if (name == null || name.trim().isEmpty()) {
		    	ViewUtils.showError("Please input a valid hotel name");
		}
		
		else {
		      // reset the driver text field if success
		      if (ViewUtils.callController(() -> 
		      ClimbSafeFeatureSet1Controller.deleteHotel(String name))) {
		    	  ViewUtils.makePopupWindow("Hotel Removed", name + " has been deleted successfully.");
		    	  
		    	  HotelDeleteTextField.setText("");
		      }
		}
		
	}
	// Event Listener on Button[#UpdateHotelButton].onAction
	@FXML
	public void updateHotel(ActionEvent event) {
		
		String oldName = OldHotelNameTextField.getText();
		String newName = NewHotelNameTextField.getText();
	    String newAddress = NewHotelAddressTextField.getText();
	    String newrating = NewStarRatingTextField.getText();
	    
	    if (oldName == null || oldName.trim().isEmpty()) {
	    	ViewUtils.showError("Please input a valid hotel name");
	    }
	    else if (newName == null || newName.trim().isEmpty()) {
	    	ViewUtils.showError("Please input a valid hotel name");
	    }
	    else if (newAddress == null || newAddress.trim().isEmpty()) {
	    	ViewUtils.showError("Please input a valid hotel address");
		}
	    else if (newrating == null || newrating.trim().isEmpty()) {
	    	ViewUtils.showError("Please input a valid hotel rating");
		}
	    else {
	      // reset the driver text field if success
	      if (ViewUtils.callController(() -> 
	      ClimbSafeFeatureSet7Controller.updateHotel(String oldName, String newName, String newAddress, Integer.valueOf(NewNrStars)))) {
	    	  ViewUtils.makePopupWindow("Hotel Updated", name + " has been updated successfully.");
	    	  
	    	  OldHotelNameTextField.setText("");
	    	  NewHotelNameTextField.setText("");
	    	  NewHotelAddressTextField.setText("");
	    	  NewStarRatingTextField.setText("");
	      }
	    }
	}
}
