package ca.mcgill.ecse.climbsafe.javafx.fxml.controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class MemberController {
	@FXML
	private Button RegisterMemberButton;
	@FXML
	private TextField UserNameTextField;
	@FXML
	private TextField EmailText;
	@FXML
	private Button UpdateMemberButton;

	// Event Listener on Button.onAction
	@FXML
	public void deleteMemberClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#RegisterMemberButton].onAction
	@FXML
	public void registerMember(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#UserNameTextField].onAction
	@FXML
	public void enterUserName(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#EmailText].onAction
	@FXML
	public void enterEmail(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#UpdateMemberButton].onAction
	@FXML
	public void updateMember(ActionEvent event) {
		// TODO Autogenerated
	}
}
