package ca.mcgill.ecse.climbsafe.javafx.fxml.controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class SetupNMCController {
	@FXML
	private TextField DiscountTextField;
	@FXML
	private TextField NumberOfWeeksTextField;
	@FXML
	private Button Initialize;

	// Event Listener on TextField[#DiscountTextField].onAction
	@FXML
	public void enterDiscount(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#NumberOfWeeksTextField].onAction
	@FXML
	public void enterNumberOfWeeks(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#Initialize].onAction
	@FXML
	public void initialize(ActionEvent event) {
		// TODO Autogenerated
	}
}
